### ISSUE TITLE
Enable/Disable data network not working

### ISSUE THREAD

**Issue by SealviewTW** [appium/io.appium.settings#4] opened 2015-03-23 08:20 UTC
I am trying to turn off my data network with the io.appium.settings/.Settings app and it doesn't seem to work. 

The command I am trying to run is: adb shell am start -n io.appium.settings/.Settings -e data off ( it prompts the correct message (Enabling / Disabling data connection), but it does not do anything (data network status remains unchanged)).

For a short discussion, and other people exepriencing the same issue, please refer to: https://discuss.appium.io/t/enable-disable-data-network-not-working/3382

**Comment by mykola-mokhnach** [comment] 2017-03-27 15:00
Possible duplicate of https://github.com/appium/io.appium.settings/issues/5

**Closed** 2018-11-02 11:14 UTC
